Repository ThugDev/PR-Deliver, pull requests merged in 2024-10, with the labels that each got.

#11 [🎁/🟢] 유저와 관련된 페이지 퍼블리싱
  app/[userId]/_components/side-nav.tsx
  app/[userId]/_components/tab-title.tsx
  app/[userId]/_components/type.ts
  app/[userId]/custom-message/page.tsx
  app/[userId]/layout.tsx
  app/[userId]/page.tsx
  app/[userId]/repo-list/_components/.gitkeep
  app/[userId]/repo-list/page.tsx
  app/_components/user-dashboard.tsx
  app/globals.css
  app/page.tsx
  components/layout/header.tsx
  constants/type.ts
  constants/user/main-dashboard.ts
  constants/user/nav-tab.ts
  public/gif/Loading-bar.json
  public/icons/purple-list.svg
  public/light/icons/list.svg
  utils/shorten-text.ts
Labels: 🧚🏻 style

#12 [🟢] OAuth2를 사용한 깃허브 로그인
  .gitignore
  apis/github-oauth.ts
  app/_components/auth-login-button.tsx
  app/_components/user-dashboard.tsx
  app/api/auth/callback/github/page.tsx
  app/page.tsx
  hook/useAuth.ts
  next.config.mjs
  package-lock.json
  package.json
  utils/auth.ts
Labels: 🟢 feat

#13 [🎁] 디자인 변경된 페이지 일괄 수정
  .eslintrc.js
  .prettierrc
  app/(webhook)/messenger/_components/method-tab.tsx
  app/(webhook)/messenger/_components/register-tab.tsx
  app/(webhook)/messenger/page.tsx
  app/[userId]/_components/side-nav.tsx
  app/[userId]/layout.tsx
  app/[userId]/type.ts
  app/_components/auth-login-button.tsx
  app/_components/user-dashboard.tsx
  app/repository/page.tsx
  components/common/input.tsx
  components/layout/tab/tab-layout.tsx
  components/layout/tab/type.ts
  constants/register/messenger-type.ts
  constants/steps/messenger.ts
  constants/type.ts
  constants/user/main-dashboard.ts
  constants/user/nav-tab.ts
  hook/.gitkeep
  package-lock.json
  package.json
  public/icons/memo.svg
  public/icons/next-arrow.svg
  public/icons/pen.svg
  public/icons/purple-message.svg
Labels: 🧚🏻 style

#14 [🟢]: repository 등록 페이지 기능 생성 완료
  apis/api-instance.ts
  apis/auth.ts
  apis/github-oauth.ts
  apis/repository.ts
  apis/type.ts
  app/api/auth/callback/github/page.tsx
  app/repository/_component/register-tab.tsx
  app/repository/_component/type.ts
Labels: 🟢 feat, 💡 refactor

#16 [🟢] : fetch logged-in user info & user's repository list
  apis/.gitkeep
  apis/api-instance.ts
  apis/auth.ts
  apis/repository.ts
  app/[userId]/repo-list/_components/.gitkeep
  app/[userId]/repo-list/_components/fetch-repo-list.tsx
  app/[userId]/repo-list/page.tsx
  app/_components/user-dashboard.tsx
  app/api/auth/callback/github/page.tsx
  app/page.tsx
  constants/type.ts
  constants/user/main-dashboard.ts
  libs/.gitkeep
  libs/zustand/user.ts
  package-lock.json
  package.json
  type/.gitkeep
  type/user.ts
Labels: 🟢 feat

#17 [🟢]: Register Web Hook and Messenger
  apis/api-instance.ts
  apis/messenger.ts
  apis/repository.ts
  apis/type.ts
  app/(webhook)/github/_component/type.ts
  app/(webhook)/github/_component/webhook-list.tsx
  app/(webhook)/github/page.tsx
  app/(webhook)/github/type.ts
  app/(webhook)/messenger/_components/register-tab.tsx
  app/(webhook)/messengers/_components/method-tab.tsx
  app/(webhook)/messengers/_components/register-tab.tsx
  app/(webhook)/messengers/page.tsx
  app/[userId]/repo-list/_components/fetch-repo-list.tsx
  app/repository/_component/register-tab.tsx
  constants/register/messenger-type.ts
  public/light/icons/up-arrow.svg
  utils/storage.ts
Labels: 🟢 feat, 🔴 remove, 🧚🏻 style, 💡 refactor

#18 Feat/modal
  app/(webhook)/github/page.tsx
  app/(webhook)/messengers/_components/register-tab.tsx
  app/repository/_component/register-tab.tsx
  components/common/button.tsx
  components/common/modal.tsx
  components/common/overlay.tsx
  components/common/type.ts
  public/icons/close.svg
  public/icons/error.svg
  public/icons/success.svg
  styles/button.css
  styles/color.ts
Labels: 🟢 feat

#19 [💡]: Isolate GitHub Page Interests
  app/(webhook)/github/_component/type.ts
  app/(webhook)/github/_component/webhook-list-content.tsx
  app/(webhook)/github/_component/webhook-list-toggle.tsx
  app/(webhook)/github/page.tsx
  app/[userId]/repo-list/_components/fetch-repo-list.tsx
  hook/useClipboard.ts
  hook/useRepository.ts
Labels: 💡 refactor

#20 [💡]: Isolating the log-in page logic
  apis/auth.ts
  app/[userId]/repo-list/_components/fetch-repo-list.tsx
  app/api/auth/callback/github/page.tsx
  app/page.tsx
  app/user-dashboard/page.tsx
  app/user-dashboard/type.ts
  components/layout/header.tsx
  libs/zustand/user.ts
  utils/storage.ts
Labels: 💡 refactor

#21 [💡]: Resolve build errors
  app/(webhook)/github/page.tsx
  app/[userId]/repo-list/_components/fetch-repo-list.tsx
  app/api/auth/callback/github/page.tsx
  hook/useRepository.ts
  utils/storage.ts
Labels: 🔥 HOTFIX, 💡 refactor

#22 [🎁/💡] : re-publish repo-list-page & refactor register-messenger-page
  app/(webhook)/messengers/_components/register-tab.tsx
  app/(webhook)/messengers/_components/register/select-container.tsx
  app/(webhook)/messengers/_components/register/type.ts
  app/[userId]/_components/side-nav.tsx
  app/[userId]/_components/tab-title.tsx
  app/[userId]/custom-message/page.tsx
  app/[userId]/layout.tsx
  app/[userId]/repo-list/_components/empty-repo-list.tsx
  app/[userId]/repo-list/_components/fetch-repo-list.tsx
  app/[userId]/repo-list/page.tsx
  app/globals.css
  components/layout/footer.tsx
  components/layout/layout.tsx
  hook/type.ts
  hook/use-messenger-registration.ts
  public/images/docs.svg
  type/messenger.ts
Labels: 🧚🏻 style, 💡 refactor
